"""Shared training configuration constants."""

# Training defaults
DEFAULT_EPOCHS = 6
DEFAULT_SAMPLES = 16384
DEFAULT_BATCH_SIZE = 32
DEFAULT_MASK_PEAK_WIDTH_SAMPLES = 10.0

# Dataset defaults
DEFAULT_WINDOW_LENGTH = 16
DEFAULT_WIDTH = 512
DEFAULT_RADII_NM = (3.0, 70.0)
DEFAULT_CONTRAST = (0.5, 1.1)
DEFAULT_NOISE_LEVEL = (0.08, 0.8)
DEFAULT_MIN_TRAJECTORIES = 2
DEFAULT_MAX_TRAJECTORIES = 3
